services:
  - type: web
    name: perna-mix-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /healthcheck
